{{- if and .Values.backup.enabled .Values.backup.bucketName .Values.backup.schedule }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ .Values.clusterName }}-scheduled-backup
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  backupOwnerReference: self
  cluster:
    name: {{ .Values.clusterName }}
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: {{ .Values.clusterName }}-objectstore
{{- end }}
